module.exports = {
  fakeData: {
    wishlist: [
    {
      name: "Teen Wolf",
      ef: 1,
      id: "16d01c97-d200-4463-b7b4-9c649c4c3a5a",
      status: "new",
      et: 12,
      episodes: {
        1: {
          1: "new",
          2: "new",
          3: "new",
          4: "new",
          5: "new",
          6: "new",
          7: "new",
          8: "new",
          9: "new",
          10: "new",
          11: "new",
          12: "new",
        },
        2: {
          1: "new",
          2: "new",
          3: "new",
          4: "new",
          5: "new",
          6: "new",
          7: "new",
          8: "new",
          9: "new",
          10: "new",
          11: "new",
          12: "new",
        },
        3: {
          1: "new",
          2: "new",
          3: "new",
          4: "new",
          5: "new",
          6: "new",
          7: "new",
          8: "new",
          9: "new",
          10: "new",
          11: "complete",
          12: "new",
          13: "new",
          14: "new",
          15: "new",
          16: "new",
          17: "new",
          18: "complete",
          19: "new",
          20: "new",
          21: "new",
          22: "complete",
          23: "new",
          24: "new",
        },
        4: {
          1: "new",
          2: "new",
          3: "new",
          4: "new",
          5: "new",
          6: "complete",
          7: "new",
          8: "complete",
          9: "complete",
          10: "new",
          11: "new",
          12: "new",
        },
      },
      imdbID: "tt1567432",
      mediaType: "series",
      imdbData: {
        imdbVotes: "130,163",
        Country: "USA",
        totalSeasons: "6",
        Writer: "Jeff Davis",
        Rated: "TV-14",
        Response: "True",
        Released: "05 Jun 2011",
        Year: "2011–2017",
        Plot: "An average high school student and his best friend get caught up in some trouble causing him to receive a werewolf bite. As a result they find themselves in the middle of all sorts of dramas in Beacon Hills.",
        Director: "N/A",
        Language: "English",
        Actors: "Tyler Posey, Holland Roden, Dylan O'Brien, Linden Ashby",
        Metascore: "N/A",
        imdbRating: "7.6",
        Ratings: [{ Source: "Internet Movie Database", Value: "7.6/10" }],
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMThlNTk3YzMtOTZjMi00M2NiLTg1NTgtYThiYzE2MDFmMDUwXkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_SX300.jpg",
        Awards: "23 wins & 39 nominations.",
        Genre: "Action, Drama, Fantasy, Romance, Thriller",
        Runtime: "41 min",
        Type: "series",
        Title: "Teen Wolf",
        imdbID: "tt1567432",
      },
      addedBy: "aegisthus",
      st: 4,
      isOngoing: false,
      dateAdded: "Tue Jun 22 2021",
      sf: 1,
      progress: { new: 100 },
      isPriority: true,
    },
    {
      mediaType: "movie",
      isPriority: false,
      imdbID: "tt0369610",
      status: "new",
      progress: "new",
      addedBy: "aegisthus",
      id: "1c524649-1c48-4ce7-945b-834c15c98f2c",
      name: "Jurassic World",
      dateAdded: "Tue Jun 22 2021",
      imdbData: {
        Title: "Jurassic World",
        Type: "movie",
        Writer: "Rick Jaffa, Amanda Silver, Colin Trevorrow",
        Production:
          "Amblin Entertainment, Universal Pictures, Legendary Pictures",
        Plot: "A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur, the Indominus Rex, which escapes containment and goes on a killing spree.",
        imdbID: "tt0369610",
        Genre: "Action, Adventure, Sci-Fi",
        Released: "12 Jun 2015",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BNzQ3OTY4NjAtNzM5OS00N2ZhLWJlOWUtYzYwZjNmOWRiMzcyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        imdbRating: "7.0",
        Rated: "PG-13",
        Response: "True",
        BoxOffice: "$652,385,625",
        DVD: "06 Sep 2016",
        Language: "English",
        Actors: "Chris Pratt, Bryce Dallas Howard, Ty Simpkins",
        Ratings: [
          { Value: "7.0/10", Source: "Internet Movie Database" },
          { Value: "71%", Source: "Rotten Tomatoes" },
          { Value: "59/100", Source: "Metacritic" },
        ],
        Metascore: "59",
        Awards: "15 wins & 58 nominations",
        imdbVotes: "590,037",
        Website: "N/A",
        Year: "2015",
        Director: "Colin Trevorrow",
        Country: "United States",
        Runtime: "124 min",
      },
    },
    {
      st: "17",
      isPriority: true,
      status: "new",
      progress: { new: 100 },
      isOngoing: false,
      ef: 1,
      name: "Grey's Anatomy",
      addedBy: "aegisthus",
      dateAdded: "Fri Jun 25 2021",
      imdbID: "tt0413573",
      episodes: {
        1: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
        },
        2: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "complete",
          17: "copied",
          18: "copied",
          19: "copied",
          20: "copied",
          21: "copied",
          22: "copied",
          23: "complete",
          24: "complete",
          25: "complete",
          26: "complete",
          27: "copied",
        },
        3: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "complete",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "copied",
          19: "complete",
          20: "complete",
          21: "copied",
          22: "copied",
          23: "copied",
          24: "copied",
          25: "copied",
        },
        4: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
        },
        5: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "complete",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "complete",
          19: "copied",
          20: "complete",
          21: "copied",
          22: "copied",
          23: "complete",
          24: "copied",
        },
        6: {
          1: "complete",
          2: "complete",
          3: "complete",
          4: "complete",
          5: "complete",
          6: "copied",
          7: "copied",
          8: "complete",
          9: "complete",
          10: "complete",
          11: "complete",
          12: "complete",
          13: "copied",
          14: "complete",
          15: "copied",
          16: "complete",
          17: "copied",
          18: "complete",
          19: "copied",
          20: "complete",
          21: "copied",
          22: "copied",
          23: "copied",
          24: "copied",
        },
        7: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "complete",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "complete",
          13: "complete",
          14: "complete",
          15: "complete",
          16: "complete",
          17: "copied",
          18: "copied",
          19: "copied",
          20: "copied",
          21: "copied",
          22: "copied",
        },
        8: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "copied",
          19: "copied",
          20: "copied",
          21: "copied",
          22: "copied",
          23: "copied",
          24: "copied",
        },
        9: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "copied",
          19: "copied",
          20: "copied",
          21: "copied",
          22: "copied",
          23: "copied",
          24: "copied",
        },
        10: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "copied",
          19: "copied",
          20: "copied",
          21: "copied",
          22: "copied",
          23: "copied",
          24: "copied",
        },
        11: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "copied",
          19: "copied",
          20: "copied",
          21: "copied",
          22: "copied",
          23: "copied",
          24: "copied",
          25: "copied",
        },
        12: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "copied",
          19: "copied",
          20: "copied",
          21: "copied",
          22: "copied",
          23: "copied",
          24: "copied",
        },
        13: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "copied",
          19: "copied",
          20: "copied",
          21: "copied",
          22: "copied",
          23: "copied",
          24: "copied",
        },
        14: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "copied",
          19: "copied",
          20: "copied",
          21: "copied",
          22: "copied",
          23: "copied",
          24: "copied",
        },
        15: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "error",
          7: "copied",
          8: "copied",
          9: "error",
          10: "copied",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "copied",
          19: "error",
          20: "copied",
          21: "copied",
          22: "copied",
          23: "copied",
          24: "copied",
          25: "copied",
        },
        16: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "copied",
          5: "copied",
          6: "copied",
          7: "copied",
          8: "copied",
          9: "copied",
          10: "error",
          11: "copied",
          12: "copied",
          13: "copied",
          14: "copied",
          15: "copied",
          16: "copied",
          17: "copied",
          18: "copied",
          19: "error",
          20: "copied",
          21: "copied",
        },
        17: {
          1: "new",
          2: "downloading",
          3: "new",
          4: "new",
          5: "complete",
          6: "new",
          7: "new",
          8: "new",
          9: "error",
          10: "new",
          11: "new",
          12: "new",
          13: "error",
          14: "new",
          15: "new",
          16: "new",
          17: "new",
        },
      },
      imdbData: {
        Writer: "Shonda Rhimes",
        Title: "Grey's Anatomy",
        Genre: "Drama, Romance",
        Plot: "A drama centered on the personal and professional lives of five surgical interns and their supervisors.",
        Awards: "Won 4 Primetime Emmys. 80 wins & 232 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMjgwNGNkZGYtMWQyYS00YjEzLWFmZTctODUzYWMxOWJkNTAzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        imdbID: "tt0413573",
        Language: "English",
        Ratings: [{ Source: "Internet Movie Database", Value: "7.5/10" }],
        imdbRating: "7.5",
        Country: "United States",
        Rated: "TV-14",
        Response: "True",
        Type: "series",
        Year: "2005–",
        Actors: "Ellen Pompeo, Chandra Wilson, James Pickens Jr.",
        totalSeasons: "17",
        Metascore: "N/A",
        Runtime: "41 min",
        Director: "N/A",
        imdbVotes: "260,106",
        Released: "27 Mar 2005",
      },
      mediaType: "series",
      sf: 1,
      et: 17,
      id: "2402b263-e813-4087-99c2-5388598c21f1",
    },
    {
      ef: 1,
      imdbID: "tt9251798",
      id: "59755ad3-9c86-4d3b-9521-013dc6eb1021",
      et: 6,
      st: "2",
      addedBy: "aegisthus",
      progress: { downloading: 16.67, new: 66.67, complete: 16.67 },
      isPriority: false,
      episodes: {
        2: {
          1: "downloading",
          2: "complete",
          3: "new",
          4: "new",
          5: "new",
          6: "new",
        },
      },
      name: "Ragnarok",
      isOngoing: false,
      sf: "2",
      imdbData: {
        Genre: "Action, Drama, Fantasy, Mystery, Thriller",
        Released: "31 Jan 2020",
        Director: "N/A",
        imdbVotes: "29,000",
        imdbRating: "7.5",
        Response: "True",
        Actors:
          "David Stakston, Jonas Strand Gravli, Herman Tømmeraas, Theresa Frostad Eggesbø",
        Rated: "TV-MA",
        Plot: "A small Norwegian town experiencing warm winters and violent downpours seems to be headed for another Ragnarok -- unless someone intervenes in time.",
        Country: "Norway, Denmark",
        Metascore: "N/A",
        Writer: "Emilie Lebech Kaae, Adam Price",
        Year: "2020–",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BODM3NTZkZTUtYzEyYS00NjEyLTg2NjEtNDhlMjYwY2ZkNGUzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        Runtime: "45 min",
        Language: "Norwegian",
        Title: "Ragnarok",
        Ratings: [{ Source: "Internet Movie Database", Value: "7.5/10" }],
        Type: "series",
        totalSeasons: "2",
        Awards: "N/A",
        imdbID: "tt9251798",
      },
      dateAdded: "Thu Jul 01 2021",
      status: "new",
      mediaType: "series",
    },
    {
      name: "Toy Story",
      imdbData: {
        Awards: "Nominated for 3 Oscars. Another 27 wins & 20 nominations.",
        Country: "USA",
        Title: "Toy Story",
        Writer:
          "John Lasseter (original story by), Pete Docter (original story by), Andrew Stanton (original story by), Joe Ranft (original story by), Joss Whedon (screenplay by), Andrew Stanton (screenplay by), Joel Cohen (screenplay by), Alec Sokolow (screenplay by)",
        Metascore: "95",
        Type: "movie",
        Language: "English",
        Website: "N/A",
        Response: "True",
        DVD: "N/A",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SX300.jpg",
        Year: "1995",
        BoxOffice: "$223,225,679",
        Ratings: [
          { Value: "8.3/10", Source: "Internet Movie Database" },
          { Value: "100%", Source: "Rotten Tomatoes" },
          { Value: "95/100", Source: "Metacritic" },
        ],
        Runtime: "81 min",
        imdbVotes: "908,401",
        imdbID: "tt0114709",
        Plot: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
        Director: "John Lasseter",
        Genre: "Animation, Adventure, Comedy, Family, Fantasy",
        Production: "Pixar Animation Studios, Walt Disney Pictures",
        Released: "22 Nov 1995",
        imdbRating: "8.3",
        Actors: "Tom Hanks, Tim Allen, Don Rickles, Jim Varney",
        Rated: "G",
      },
      status: "new",
      isPriority: false,
      imdbID: "tt0114709",
      dateAdded: "Thu Jul 01 2021",
      id: "59e38bff-6c19-47ad-9fa2-f3331fd40d4d",
      mediaType: "movie",
      progress: "new",
      addedBy: "aegisthus",
    },
    {
      isOngoing: false,
      addedBy: "aegisthus",
      ef: 1,
      episodes: {
        10: {
          1: "new",
          2: "new",
          3: "new",
          4: "downloading",
          5: "new",
          6: "complete",
          7: "new",
          8: "new",
          9: "complete",
          10: "new",
          11: "new",
          12: "new",
          13: "error",
          14: "new",
          15: "new",
          16: "downloading",
          17: "new",
          18: "new",
          19: "new",
          20: "new",
          21: "new",
          22: "new",
        },
        11: { 1: "new" },
      },
      imdbData: {
        Writer: "Frank Darabont, Angela Kang",
        Country: "United States",
        Language: "English",
        Plot: "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.",
        Runtime: "44 min",
        totalSeasons: "11",
        Title: "The Walking Dead",
        imdbRating: "8.2",
        Genre: "Drama, Horror, Thriller",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMTc5ZmM0OTQtNDY4MS00ZjMyLTgwYzgtOGY0Y2VlMWFmNDU0XkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg",
        Metascore: "N/A",
        imdbID: "tt1520211",
        Director: "N/A",
        Rated: "TV-14",
        Type: "series",
        Response: "True",
        Actors: "Andrew Lincoln, Norman Reedus, Melissa McBride",
        Released: "31 Oct 2010",
        Awards: "Won 2 Primetime Emmys. 78 wins & 222 nominations total",
        imdbVotes: "872,702",
        Year: "2010–2022",
        Ratings: [{ Source: "Internet Movie Database", Value: "8.2/10" }],
      },
      mediaType: "series",
      isPriority: false,
      dateAdded: "Fri Jun 25 2021",
      status: "new",
      name: "The Walking Dead",
      progress: { new: 100 },
      imdbID: "tt1520211",
      sf: "10",
      id: "62a4c065-5326-4bc1-879a-825c8b6e96a8",
      et: 1,
      st: 11,
    },
    {
      id: "6354ed6f-5572-48aa-99d2-2617b2d4cf9a",
      status: "new",
      name: "The Bourne Identity",
      imdbID: "tt0258463",
      addedBy: "aegisthus",
      isPriority: false,
      dateAdded: "Thu Jul 01 2021",
      mediaType: "movie",
      progress: "new",
      imdbData: {
        Actors: "Franka Potente, Matt Damon, Chris Cooper",
        Year: "2002",
        Type: "movie",
        Released: "14 Jun 2002",
        Rated: "PG-13",
        Title: "The Bourne Identity",
        Genre: "Action, Mystery, Thriller",
        imdbID: "tt0258463",
        Response: "True",
        BoxOffice: "$121,661,683",
        Plot: "A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and attempting to regain his memory.",
        Website: "N/A",
        Awards: "3 wins & 6 nominations",
        imdbVotes: "516,256",
        Ratings: [
          { Source: "Internet Movie Database", Value: "7.9/10" },
          { Source: "Rotten Tomatoes", Value: "83%" },
          { Source: "Metacritic", Value: "68/100" },
        ],
        Writer: "Tony Gilroy, W. Blake Herron, Robert Ludlum",
        DVD: "22 Jul 2015",
        Country: "United States, Germany, Czech Republic, France",
        Production: "Hypnotic, Universal Pictures, Stillking Films",
        Director: "Doug Liman",
        Metascore: "68",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BM2JkNGU0ZGMtZjVjNS00NjgyLWEyOWYtZmRmZGQyN2IxZjA2XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
        Runtime: "119 min",
        imdbRating: "7.9",
        Language: "English, French, German, Dutch, Italian, Yoruba",
      },
    },
    {
      et: 8,
      episodes: { 1: { 1: "new", 2: "new" } },
      mediaType: "series",
      dateAdded: "Thu Jul 01 2021",
      isOngoing: false,
      progress: { new: 100 },
      addedBy: "aegisthus",
      ef: 1,
      isPriority: false,
      status: "new",
      sf: 1,
      st: "1",
      imdbID: "tt11102190",
      imdbData: {
        Writer: "Sigurjón Kjartansson, Baltasar Kormákur",
        Genre: "Drama, Mystery, Sci-Fi, Thriller",
        Metascore: "N/A",
        Actors:
          "Guðrún Ýr Eyfjörð, Íris Tanja Flygenring, Ingvar Sigurdsson, Aliette Opheim",
        imdbRating: "7.3",
        imdbVotes: "2,232",
        Title: "Katla",
        Ratings: [{ Source: "Internet Movie Database", Value: "7.3/10" }],
        Awards: "N/A",
        Runtime: "N/A",
        Response: "True",
        Country: "Iceland",
        Plot: "One year after the violent eruption of the subglacial volcano Katla, the peace and tranquility in the small town of Vik is dramatically disturbed.",
        Language: "Icelandic",
        Year: "2021–",
        imdbID: "tt11102190",
        Type: "series",
        Released: "17 Jun 2021",
        Director: "N/A",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BNGIyYWIzODQtMzU5Ni00YmIxLTk0YzAtOTg3ZWEwNjQ4OTQ4XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg",
        Rated: "TV-MA",
        totalSeasons: "1",
      },
      id: "9aaa4f5a-6ce1-4a3f-9a82-847ac94630ef",
      name: "Katla",
    },
    {
      status: "new",
      id: "d4dfe65e-9862-4206-8ec9-3ac2e21a458c",
      imdbData: {
        Production: "Universal Pictures, Amblin Entertainment",
        Genre: "Action, Adventure, Sci-Fi, Thriller",
        Website: "N/A",
        Response: "True",
        Year: "1993",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg",
        Awards: "Won 3 Oscars. Another 42 wins & 27 nominations.",
        BoxOffice: "$404,214,720",
        Writer:
          "Michael Crichton (novel), Michael Crichton (screenplay), David Koepp (screenplay)",
        Title: "Jurassic Park",
        Ratings: [
          { Value: "8.1/10", Source: "Internet Movie Database" },
          { Value: "92%", Source: "Rotten Tomatoes" },
          { Value: "68/100", Source: "Metacritic" },
        ],
        imdbRating: "8.1",
        Rated: "PG-13",
        imdbID: "tt0107290",
        Actors: "Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough",
        Runtime: "127 min",
        Metascore: "68",
        Director: "Steven Spielberg",
        Plot: "A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
        Type: "movie",
        DVD: "18 May 2015",
        Released: "11 Jun 1993",
        imdbVotes: "889,308",
        Language: "English, Spanish",
        Country: "USA",
      },
      dateAdded: "Thu Jul 01 2021",
      addedBy: "aegisthus",
      progress: "new",
      imdbID: "tt0107290",
      name: "Jurassic Park",
      isPriority: false,
      mediaType: "movie",
    },
    {
      sf: "3",
      imdbID: "tt2234222",
      status: "downloading",
      isOngoing: false,
      name: "Orphan Black",
      st: 5,
      et: 10,
      progress: { new: 100 },
      dateAdded: "Fri Jun 25 2021",
      id: "d8c6b64e-2a07-489f-8b3b-6c0cbe8476ab",
      addedBy: "aegisthus",
      ef: 1,
      isPriority: false,
      episodes: {
        3: {
          1: "new",
          2: "new",
          3: "complete",
          4: "new",
          5: "new",
          6: "new",
          7: "complete",
          8: "new",
          9: "new",
          10: "new",
        },
        4: {
          1: "copied",
          2: "copied",
          3: "copied",
          4: "new",
          5: "copied",
          6: "new",
          7: "new",
          8: "new",
          9: "new",
          10: "new",
        },
        5: {
          1: "new",
          2: "new",
          3: "complete",
          4: "copied",
          5: "new",
          6: "copied",
          7: "new",
          8: "complete",
          9: "new",
          10: "new",
        },
      },
      imdbData: {
        Awards: "Won 1 Primetime Emmy. Another 67 wins & 94 nominations.",
        Ratings: [{ Value: "8.3/10", Source: "Internet Movie Database" }],
        Year: "2013–2017",
        Country: "Canada",
        Plot: "A streetwise hustler is pulled into a compelling conspiracy after witnessing the suicide of a girl who looks just like her.",
        Director: "N/A",
        Actors:
          "Tatiana Maslany, Jordan Gavaris, Maria Doyle Kennedy, Kristian Bruun",
        Writer:
          "Kim Coghill, Andrew De Angelis, Jeff Detsky, John Fawcett, Adam Higgs, Alex Levine, Bob Mackowycz Jr., Graeme Manson, Elize Morgan, Peter Rowley, Rebecca Sernasie",
        imdbID: "tt2234222",
        Language: "English",
        imdbRating: "8.3",
        Rated: "TV-MA",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BZjM1ZTVlMGYtNjVkZS00OGMzLWFjMmYtYTE3NjJhZDRlODY3XkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_SX300.jpg",
        Title: "Orphan Black",
        imdbVotes: "103,529",
        Runtime: "44 min",
        Response: "True",
        Metascore: "N/A",
        Released: "30 Mar 2013",
        totalSeasons: "5",
        Genre: "Action, Drama, Sci-Fi",
        Type: "series",
      },
      mediaType: "series",
    },
    {
      mediaType: "series",
      dateAdded: "Thu Jul 01 2021",
      et: 6,
      episodes: {
        3: { 1: "new", 2: "new", 3: "new", 4: "new", 5: "new", 6: "new" },
      },
      isOngoing: false,
      sf: "3",
      addedBy: "aegisthus",
      imdbID: "tt0262150",
      isPriority: false,
      imdbData: {
        totalSeasons: "3",
        Year: "2000–2004",
        Released: "09 Dec 2001",
        imdbVotes: "55,167",
        Runtime: "25 min",
        Title: "Black Books",
        Genre: "Comedy",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BODZjOGMxMGUtYTY3YS00NjcxLWFkY2EtYzc3NDVkZjk0YWY2XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
        imdbID: "tt0262150",
        Country: "United Kingdom",
        Metascore: "N/A",
        Writer: "Dylan Moran",
        Director: "N/A",
        Plot: "Bernard Black runs a book shop, though his customer service skills leave something to be desired. He hires Manny as an employee. Fran runs the shop next door. Between the three of them many adventures ensue.",
        Ratings: [{ Value: "8.5/10", Source: "Internet Movie Database" }],
        Awards: "3 wins & 3 nominations total",
        imdbRating: "8.5",
        Response: "True",
        Rated: "TV-PG",
        Type: "series",
        Language: "English",
        Actors: "Dylan Moran, Bill Bailey, Tamsin Greig",
      },
      status: "new",
      id: "e6016d3f-e46c-4065-9042-446b920a7f8e",
      progress: { new: 100 },
      ef: 1,
      st: "3",
      name: "Black Books",
    }
  ],
    // messages: [
    //   {msgType: "custom",
    //   custommsgContent: "This is a test message 1",
    //   entryStatusUpdate: "custom",
    //   id: "message4",
    //   usersVis: {
    //     guest: true,
    //     aegisthus: true,
    //     testuser1: true,
    //     testuser2: false
    //   },
    //   affectedEntry: "Teen Wolf"},
    //   {msgType: "status",
    //   id: "message1",
    //   custommsgContent: "This is a test message 1",
    //   entryStatusUpdate: "downloading",
    //   usersVis: {
    //     guest: true,
    //     aegisthus: true,
    //     testuser1: true,
    //     testuser2: false
    //   },
    //   affectedEntry: "Black Books"},
    //   {msgType: "custom",
    //   id: "message2",
    //   custommsgContent: "This is a test message 2",
    //   entryStatusUpdate: "custom",
    //   usersVis: {
    //     guest: true,
    //     aegisthus: true,
    //     testuser1: true,
    //     testuser2: false
    //   },
    //   affectedEntry: "Tom Clancy"}
    // ],
    messages: [
      {
      "id": "12345",
      "msgType": "status",
      "msgContent": "new",
      "mailed": false,
      "read": false,
      "msgRecipient": "aegisthus",
      "affectedEntry": "Finding Nemo",
      "affectedEpisodes": [0,0,0,0]
    },
    {
      "id": "24246262",
      "msgType": "custom",
      "msgContent": "This is a custom test message.",
      "mailed": false,
      "read": false,
      "msgRecipient": "testuser1",
      "affectedEntry": "title",
      "affectedEpisodes": ["sf", "ef", "st", "et"]
    },
    {
      "id": "234567821",
      "msgType": "status",
      "msgContent": "downloading",
      "mailed": false,
      "read": false,
      "msgRecipient": "testuser1",
      "affectedEntry": "Teen Wolf",
      "affectedEpisodes": [1,4,2,5]
    },
    {
      "id": "29348766987423",
      "msgType": "custom",
      "msgContent": "text goes here",
      "mailed": false,
      "read": false,
      "msgRecipient": "testuser1",
      "affectedEntry": "Affected Entry",
      "affectedEpisodes": [0,0,0,0]
    },
    {
      "id": "29348766987423",
      "msgType": "custom",
      "msgContent": "This message has been read.",
      "mailed": false,
      "read": true,
      "msgRecipient": "aegisthus",
      "affectedEntry": "Affected Entry",
      "affectedEpisodes": [0,0,0,0]
    }
    ],
    users: [
      {
        details: {
          "name": "Matthew",
          "email": "quirinustech@gmail.com"
          },
        password: "$2b$10$N36n13bELXeUnr5S/bfvfugBvScs36FGrRyDiMl9UyXEzqr8q/4g.",
        privileges: {
          can_add: true,
          is_active_user: true,
          is_admin: true
        },
        userId: "00e5cdf2-ba44-4e1f-bac2-5d222703ad9b",
        username: "aegisthus",
        preferences: {
          "language": "EN",
          "display_message_centre": true
        }
      },
      {
        "userId": "5d222703ad9b-bac2-4e1f-ba44-00e5cdf2",
        "username": "testuser1",
        "details": {
            "name": "testuser1",
            "email": "testuser1@alexandria.com"
          },
        "privileges": {
          "can_add": true,
          "is_active_user": true,
          "is_admin": false
        },
        "password": "hashed and salted",
        "preferences": {
          "language": "EN",
          "display_message_centre": true
          }
      },
      {
        "userId": "00e5cdf2-zaff-usrf-cab2-5d111975ad5b",
        "username": "testuser2",
        "details": {
            "name": "testuser2",
            "email": "testuser2@alexandria.com"
          },
        "privileges": {
          "can_add": false,
          "is_active_user": false,
          "is_admin": false
        },
        "password": "hashed and salted",
        "preferences": {
          "language": "ZH",
          "display_message_centre": true
          }
      },
      {
        "userId": "00e53652-ba44-4epf-1112-5d342703ad9b",
        "username": "testuser9",
        "details": {
            "name": "testuser9",
            "email": "testuser9@alexandria.com"
          },
        "privileges": {
          "can_add": false,
          "is_active_user": false,
          "is_admin": false
        },
        "password": "hashed and salted",
        "preferences": {
          "language": "DE",
          "display_message_centre": true
          }
      }
    
      
    ],
    allPossibleStatuses : [
  "error", //red
  "failed", // cyan
  "postponed", //orange
  "new", //aqua
  "downloading", //yellow
  "complete", //green
  "copied", // grey
],
  blacklist: []
  },
};
