function MassImport() {
  let FinalList = [];

  // read old db + archive
  // make a single array 'bigDbArray'
  let bigDbArray = JSON.parse([
  {
    "st": "11",
    "poster": "",
    "et": "61",
    "ef": "1",
    "year": "2019",
    "Date": "2021/6/24-19:58",
    "series": "MasterChef AU S11",
    "genre": "cooking",
    "status": "processing",
    "id": "MC_AU_S11",
    "type": "series",
    "sf": "11"
  },
  {
    "type": "series",
    "et": "39",
    "st": "13",
    "sf": "13",
    "year": "2020",
    "series": "MasterChef AU S13",
    "poster": "",
    "Date": "2021/5/13-7:54",
    "status": "copied",
    "genre": "cooking",
    "ef": "24",
    "id": "MC_AU_S13"
  },
  {
    "Date": "2021/4/21-11:35",
    "genre": "cooking",
    "poster": "",
    "sf": "9",
    "type": "series",
    "status": "copied",
    "year": "2014-",
    "et": "all",
    "id": "TT1694423_S09",
    "series": "MasterChef USA S09",
    "ef": "1",
    "st": "9"
  },
  {
    "Date": "2021/7/1-21:13",
    "sf": "1",
    "status": "copied",
    "genre": "",
    "id": "TT5028002_S01",
    "year": "2016–2018",
    "et": "all",
    "series": "Startup",
    "st": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTAxNTIwNzE5MTJeQTJeQWpwZ15BbWU4MDE2NDQ2MTMy._V1_SX300.jpg",
    "ef": "1",
    "type": "series"
  },
  {
    "id": "masterchef_au_s12",
    "type": "series",
    "st": "12",
    "sf": "12",
    "poster": "",
    "series": "Masterchef Australia S12",
    "status": "copied",
    "ef": "1",
    "Date": "2021/5/12-8:10",
    "et": "61",
    "genre": "reality",
    "year": "2020"
  },
  {
    "year": "1977",
    "id": "tt0076137",
    "type": "movie",
    "genre": "",
    "status": "copied",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTllNTk2YWItYmQ5Yy00MGUzLTgxMzAtMjNmOTU1ODgxOGI4L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg",
    "priority": "false",
    "series": "Herbie Goes to Monte Carlo",
    "Date": "2021/6/14-19:12",
    "et": "0"
  },
  {
    "year": "1998",
    "id": "tt0133985",
    "status": "copied",
    "et": "0",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjE0Njc5NDU5Ml5BMl5BanBnXkFtZTcwOTc4OTkxMQ@@._V1_SX300.jpg",
    "series": "A Murder of Crows",
    "Date": "2021/3/03-09:03",
    "st": "",
    "ef": "",
    "type": "movie",
    "genre": "",
    "sf": ""
  },
  {
    "type": "series",
    "id": "tt0247082",
    "et": "all",
    "year": "2000–2015",
    "Date": "2021/9/14-21:50",
    "genre": "",
    "ef": "1",
    "sf": "11",
    "series": "CSI: Crime Scene Investigation",
    "status": "processing",
    "st": "15",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjRlZjFmNTktYzg0ZC00OWJlLWJlN2EtOGQ1OTRiOTFiMWE3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg"
  },
  {
    "type": "series",
    "status": "copied",
    "st": "1",
    "Date": "2021/1/21-18:47",
    "ef": "1",
    "priority": "false",
    "id": "tt0303461",
    "genre": "",
    "et": "all",
    "sf": "1",
    "year": "2002–2003",
    "series": "Firefly",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTcwNzkwMDItZmM1OC00MmQ2LTgxYjgtOTNiNDgxZDAxMjk0XkEyXkFqcGdeQXVyNDQ0MTYzMDA@._V1_SX300.jpg"
  },
  {
    "id": "tt0379786",
    "sf": "",
    "status": "copied",
    "genre": "",
    "Date": "2021/1/21-18:48",
    "st": "",
    "et": "",
    "year": "2005",
    "series": "Serenity",
    "poster": "https://m.media-amazon.com/images/M/MV5BOWE2MDAwZjEtODEyOS00ZjYyLTgzNDUtYmNiY2VmNWRiMTQxXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    "ef": "",
    "type": "movie"
  },
  {
    "type": "series",
    "genre": "",
    "et": "all",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjgwNGNkZGYtMWQyYS00YjEzLWFmZTctODUzYWMxOWJkNTAzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "sf": "17",
    "Date": "2021/6/25-19:29",
    "st": "17",
    "series": "Grey's Anatomy",
    "year": "2005–",
    "id": "tt0413573",
    "priority": "false",
    "status": "copied",
    "ef": "15"
  },
  {
    "type": "movie",
    "status": "copied",
    "genre": "",
    "year": "2007",
    "id": "tt0499554",
    "Date": "2021/8/02-19:55",
    "priority": "false",
    "series": "Reno 911!: Miami",
    "et": "0",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjkwOTk3MTAyNV5BMl5BanBnXkFtZTcwNjY5NzkyMw@@._V1_SX300.jpg"
  },
  {
    "status": "copied",
    "type": "movie",
    "priority": "false",
    "Date": "2021/8/21-10:31",
    "year": "2021",
    "id": "tt0870154",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDE1MGRlNTQtZjc4ZC00MTI0LWEwY2MtODk1YTM2NmFmYTNmXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    "et": "0",
    "series": "Jungle Cruise",
    "genre": ""
  },
  {
    "poster": "https://m.media-amazon.com/images/M/MV5BOGFlNTdmYWQtM2IzMi00YTY3LTlmMDQtZDI5NGQ5MjYzZmEwXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg",
    "year": "2021",
    "Date": "2021/3/03-09:03",
    "priority": "false",
    "genre": "",
    "status": "copied",
    "type": "movie",
    "et": "0",
    "id": "tt10016180",
    "series": "The Little Things"
  },
  {
    "et": "0",
    "type": "movie",
    "genre": "",
    "priority": "false",
    "status": "copied",
    "Date": "2021/4/18-17:02",
    "series": "Thunder Force",
    "id": "tt10121392",
    "poster": "https://m.media-amazon.com/images/M/MV5BMWZkM2I2NjEtNWM0Mi00MTgwLWJlYTAtYmNkZWYzNmQ1ZTBiXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    "year": "2021"
  },
  {
    "series": "Mare of Easttown",
    "genre": "",
    "et": "all",
    "type": "series",
    "status": "copied",
    "priority": "false",
    "sf": "1",
    "id": "tt10155688",
    "year": "2021",
    "st": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjIyOGU1NzAtODZmYi00NGMzLWJiMjItNGNjNTFjOTM5ZDJhXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "ef": "2",
    "Date": "2021/8/02-20:24"
  },
  {
    "genre": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTFmNTI1NGQtYTg1MS00MTg2LWI2NGMtNzdhMTk0OTk1MmZhXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    "id": "tt10228134",
    "Date": "2021/8/02-19:49",
    "type": "movie",
    "priority": "false",
    "et": "0",
    "status": "copied",
    "year": "2021",
    "series": "Jolt"
  },
  {
    "id": "tt10323338",
    "genre": "",
    "sf": "1",
    "status": "copied",
    "type": "series",
    "st": "2",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjNhNTI0ZTItNTJlMC00ZDI3LWEzNmYtYWFlODUwYjYxNGU3XkEyXkFqcGdeQXVyMjYwNDA2MDE@._V1_SX300.jpg",
    "year": "2020–",
    "et": "all",
    "ef": "1",
    "series": "9-1-1: Lone Star",
    "Date": "2021/8/02-19:57"
  },
  {
    "st": "2",
    "year": "2019–2021",
    "type": "series",
    "priority": "false",
    "sf": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BYTk5ZjI0M2MtYjQ5Ny00OWJmLWExYWEtNjRlMTdkNjYwMGIzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "status": "copied",
    "series": "All Rise",
    "genre": "",
    "Date": "2021/8/02-20:00",
    "id": "tt10329042",
    "ef": "10",
    "et": "all"
  },
  {
    "ef": "",
    "genre": "",
    "Date": "2021/4/18-17:03",
    "et": "0",
    "year": "2021",
    "sf": "",
    "type": "movie",
    "id": "tt10333426",
    "st": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BYmFjNWY5NjQtMTJiNC00NjFlLWIxMGQtNzhmMmQ0MjhiZjQyXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "status": "copied",
    "series": "Bliss"
  },
  {
    "series": "Blithe Spirit",
    "year": "2020",
    "id": "tt10334148",
    "et": "0",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjhjNjVmNGYtOTU2MC00ZTJlLTg5ZjMtNDk5MjZmYmVhMWEyXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    "genre": "",
    "Date": "2021/3/10-22:45",
    "type": "movie",
    "priority": "false",
    "status": "copied"
  },
  {
    "Date": "2021/7/18-11:50",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDQwYjJjODMtOWNmNC00NDJjLThiNDgtNzVkOTM1MjY5NDQ5XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "et": "0",
    "id": "tt10539608",
    "type": "movie",
    "st": "",
    "ef": "",
    "sf": "",
    "series": "The Midnight Sky",
    "year": "2020",
    "status": "copied",
    "genre": ""
  },
  {
    "ef": "1",
    "et": "all",
    "priority": "false",
    "st": "1",
    "status": "copied",
    "year": "2021–",
    "Date": "2021/6/12-10:22",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjBiM2Y2MGQtZGFhMi00ODE2LWJhNjEtOTBiNTgxZmE2N2M1XkEyXkFqcGdeQXVyMTMxNzQ2NTk1._V1_SX300.jpg",
    "sf": "1",
    "genre": "",
    "series": "Clarkson's Farm",
    "type": "series",
    "id": "tt10541088"
  },
  {
    "status": "complete",
    "series": "Clickbait",
    "Date": "2021/9/01-19:24",
    "type": "series",
    "st": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTU2OGI4YWItMTYxZi00MzU3LThiYjItZTcyNDMyZjI1MDNmXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "et": "8",
    "id": "tt10888878",
    "year": "2021",
    "genre": "",
    "sf": "1",
    "ef": "1"
  },
  {
    "poster": "https://m.media-amazon.com/images/M/MV5BYjg2YTFjMzAtNTU1My00MWY2LTg4OGEtNmE5YjFhZjY2ZDlmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    "st": "1",
    "year": "2021–",
    "status": "copied",
    "sf": "1",
    "series": "The Mosquito Coast",
    "genre": "",
    "id": "tt11041132",
    "et": "5",
    "ef": "1",
    "Date": "2021/5/14-19:50",
    "type": "series"
  },
  {
    "status": "copied",
    "genre": "",
    "ef": "1",
    "id": "tt11640020",
    "type": "series",
    "Date": "2021/8/02-19:48",
    "year": "2021",
    "et": "all",
    "poster": "https://m.media-amazon.com/images/M/MV5BNmJlYTdhZTctYmFkMS00ZmY1LWExYzgtNWU2Mzc0YmU1NmQxXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_SX300.jpg",
    "priority": "false",
    "st": "1",
    "series": "Debris",
    "sf": "1"
  },
  {
    "st": "1",
    "type": "series",
    "ef": "12",
    "year": "2020–",
    "status": "copied",
    "Date": "2021/4/18-16:59",
    "sf": "1",
    "et": "16",
    "poster": "https://m.media-amazon.com/images/M/MV5BZWY1N2E3OTItODU2Zi00YjcxLTk5MTctNzI1OWJmMDA0Mzk0XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "series": "Big Sky",
    "genre": "",
    "id": "tt11794642"
  },
  {
    "status": "copied",
    "type": "movie",
    "series": "Till Death",
    "genre": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BZGE1YjdlYzUtNGRkNC00MWFmLWI3OTEtMTA4YmNiMjU2NDAwXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_SX300.jpg",
    "Date": "2021/8/02-19:53",
    "year": "2021",
    "et": "0",
    "id": "tt11804152",
    "priority": "false"
  },
  {
    "genre": "",
    "id": "tt11828492",
    "status": "copied",
    "Date": "2021/8/02-19:53",
    "sf": "1",
    "priority": "false",
    "et": "all",
    "series": "Physical",
    "ef": "1",
    "type": "series",
    "poster": "https://m.media-amazon.com/images/M/MV5BY2FhODU2NTAtYmY2YS00ZjA3LTg2MzQtODY5ZDY0MTU0ZThiXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    "st": "1",
    "year": "2021–"
  },
  {
    "status": "copied",
    "st": "1",
    "id": "tt11937816",
    "series": "Who Killed Sara?",
    "genre": "",
    "type": "series",
    "poster": "https://m.media-amazon.com/images/M/MV5BYWZlOTM3ZjAtZDlkOC00ZjRlLWI0YTEtYTk0NzFjMWEzMDczXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg",
    "ef": "1",
    "year": "2021–",
    "sf": "1",
    "Date": "2021/5/29-11:33",
    "et": "all"
  },
  {
    "series": "An Unknown Compelling Force",
    "type": "movie",
    "poster": "https://m.media-amazon.com/images/M/MV5BMWIyYzlkZjEtZmRiOC00YWM0LThkYmItZWFhYzcyOTFmZTYwXkEyXkFqcGdeQXVyMzc2MDg3Njg@._V1_SX300.jpg",
    "et": "0",
    "genre": "",
    "Date": "2021/6/17-20:26",
    "year": "2021",
    "status": "copied",
    "priority": "false",
    "id": "tt12617712"
  },
  {
    "et": "all",
    "priority": "false",
    "sf": "1",
    "st": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTk4ZDRhYzEtZWExNy00MjIyLTgyYmMtN2Y2MzA4YzZhZTZmXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    "series": "Sweet Tooth",
    "ef": "1",
    "id": "tt12809988",
    "Date": "2021/6/06-12:28",
    "genre": "",
    "type": "series",
    "status": "copied",
    "year": "2021–"
  },
  {
    "year": "2021–",
    "ef": "1",
    "id": "tt13138834",
    "type": "series",
    "priority": "false",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjM5N2RlNDgtNjM0OS00N2ZhLWJlYjgtNTdmNDVjMWM1ZmUzXkEyXkFqcGdeQXVyNjI2OTgxNzY@._V1_SX300.jpg",
    "status": "copied",
    "series": "Time",
    "et": "all",
    "sf": "1",
    "genre": "",
    "st": "1",
    "Date": "2021/7/18-11:53"
  },
  {
    "et": "0",
    "genre": "",
    "type": "movie",
    "Date": "2021/1/22-15:16",
    "status": "copied",
    "series": "Midnight at the Magnolia",
    "poster": "https://m.media-amazon.com/images/M/MV5BZDI0MDk0ZDAtZjA5NC00MjE1LTg5ZjYtMGJjMWQ0MWI1ZDIzXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg",
    "priority": "false",
    "id": "tt13318052",
    "year": "2020"
  },
  {
    "status": "copied",
    "et": "12",
    "ef": "1",
    "type": "series",
    "poster": "https://m.media-amazon.com/images/M/MV5BMGQzNGIzNmEtNWE3ZS00OTUyLTg3YTEtMDY3NDViZWE0YWY1XkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_SX300.jpg",
    "series": "NCIS: Los Angeles",
    "st": "12",
    "genre": "",
    "id": "tt1378167",
    "sf": "9",
    "year": "2009–",
    "Date": "2021/3/02-21:26"
  },
  {
    "series": "Murder Among the Mormons",
    "status": "copied",
    "Date": "2021/7/18-11:54",
    "ef": "1",
    "st": "1",
    "genre": "",
    "et": "all",
    "sf": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTAzYzQxY2QtNTgxYS00MmM1LThmZjQtMTRlNDE1ODkzNjY5XkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg",
    "id": "tt13987620",
    "year": "2021",
    "type": "series"
  },
  {
    "status": "copied",
    "Date": "2021/5/12-08:12",
    "genre": "",
    "id": "tt1433870",
    "poster": "https://m.media-amazon.com/images/M/MV5BYmJiMGIwMWYtMzZmOS00NGEyLWE2ZjktOWM0NDdjNTgzZTBjXkEyXkFqcGdeQXVyMTAwMzM3NDI3._V1_SX300.jpg",
    "et": "23",
    "sf": "13",
    "type": "series",
    "series": "MasterChef Australia S13",
    "ef": "1",
    "st": "13",
    "year": "2009–"
  },
  {
    "type": "series",
    "Date": "2021/6/25-19:27",
    "ef": "18",
    "year": "2010–2022",
    "st": "10",
    "id": "tt1520211",
    "sf": "10",
    "series": "The Walking Dead",
    "et": "22",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTc5ZmM0OTQtNDY4MS00ZjMyLTgwYzgtOGY0Y2VlMWFmNDU0XkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg",
    "genre": "",
    "status": "copied"
  },
  {
    "genre": "",
    "id": "tt1586680",
    "Date": "2021/3/14-14:44",
    "series": "Shameless",
    "year": "2011–2021",
    "type": "series",
    "et": "8",
    "poster": "https://m.media-amazon.com/images/M/MV5BZGFiOGY1MjAtNWM2Yy00YzBlLTkwODktMTZiOWMyZmNmZmZhXkEyXkFqcGdeQXVyOTA3MTMyOTk@._V1_SX300.jpg",
    "status": "copied",
    "st": "11",
    "ef": "1",
    "sf": "9"
  },
  {
    "status": "copied",
    "series": "MasterChef USA S6,7,8,10",
    "et": "all",
    "ef": "1",
    "genre": "reality",
    "sf": "6",
    "id": "tt1694423",
    "type": "series",
    "Date": "2021/4/4-1:15",
    "year": "2014-",
    "st": "10",
    "poster": ""
  },
  {
    "status": "copied",
    "series": "The Stand",
    "type": "series",
    "priority": "false",
    "ef": "1",
    "year": "2020–2021",
    "genre": "",
    "Date": "2021/3/02-20:52",
    "id": "tt1831804",
    "et": "all",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjNjNDdhZGUtZWZmZS00ZDk3LTg0MzQtZmU5MDExY2Q1ZjYzXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg",
    "st": "1",
    "sf": "1"
  },
  {
    "sf": "9",
    "ef": "1",
    "type": "series",
    "genre": "",
    "status": "copied",
    "st": "9",
    "series": "American Horror Story",
    "poster": "https://m.media-amazon.com/images/M/MV5BODZlYzc2ODYtYmQyZS00ZTM4LTk4ZDQtMTMyZDdhMDgzZTU0XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_SX300.jpg",
    "id": "tt1844624",
    "Date": "2020/11/15-15:40",
    "year": "2011–",
    "et": "9"
  },
  {
    "status": "processing",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTQ0NGFkYmUtODQ2YS00N2FiLWIyNWUtNmJjMDkzMjVlNzIyXkEyXkFqcGdeQXVyMDE4MzA0NQ@@._V1_SX300.jpg",
    "genre": "",
    "type": "series",
    "st": "11",
    "year": "2010–",
    "id": "tt1877368",
    "ef": "1",
    "et": "10",
    "series": "The Great British Bake Off",
    "Date": "2021/8/21-10:29",
    "sf": "8"
  },
  {
    "series": "Modern Persuasion",
    "et": "0",
    "priority": "false",
    "status": "copied",
    "genre": "",
    "id": "tt2165922",
    "poster": "https://m.media-amazon.com/images/M/MV5BNmNlYjcyYmMtNzNhOS00MzM4LWExODgtNGJiM2VjODZmZDBhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "year": "2020",
    "type": "movie",
    "Date": "2021/6/12-10:24"
  },
  {
    "type": "series",
    "id": "tt2177268",
    "status": "copied",
    "genre": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BNGM3NDBhMWMtODc5Mi00ZWY2LTgyNTgtNDAzNTIzNzhmMGE1XkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg",
    "st": "1",
    "Date": "2021/3/27-15:00",
    "series": "Clarice",
    "sf": "1",
    "et": "9",
    "ef": "8",
    "year": "2021–"
  },
  {
    "type": "movie",
    "priority": "false",
    "Date": "2021/6/21-22:04",
    "status": "copied",
    "year": "2020",
    "et": "0",
    "id": "tt2222042",
    "poster": "https://m.media-amazon.com/images/M/MV5BYWVkMWEyMDUtZTVmOC00MTYxLWE1ZTUtNjk4M2IzMjY2OTIxXkEyXkFqcGdeQXVyMDk5Mzc5MQ@@._V1_SX300.jpg",
    "series": "Love and Monsters",
    "genre": ""
  },
  {
    "year": "2012–",
    "status": "copied",
    "st": "9",
    "genre": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BM2Q1MDhjYzQtZmNmYS00ZmUyLWFmYjgtZTkyMzU0ZjcyMDNmXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_SX300.jpg",
    "id": "tt2261391",
    "et": "all",
    "sf": "9",
    "Date": "2021/8/02-20:17",
    "series": "Chicago Fire",
    "ef": "1",
    "type": "series"
  },
  {
    "sf": "8",
    "series": "Wentworth",
    "st": "8",
    "Date": "2021/2/15-22:42",
    "genre": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BZDkxZmFhMDAtMmIyZS00NjAwLThlYjctZDQwMWQwYzdlYWY4XkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_SX300.jpg",
    "year": "2013–2021",
    "ef": "9",
    "priority": "false",
    "status": "copied",
    "et": "9",
    "id": "tt2433738",
    "type": "series"
  },
  {
    "st": "",
    "genre": "",
    "series": "Bird Box",
    "year": "2018",
    "sf": "",
    "ef": "",
    "et": "0",
    "id": "tt2737304",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjAzMTI1MjMyN15BMl5BanBnXkFtZTgwNzU5MTE2NjM@._V1_SX300.jpg",
    "Date": "2021/3/03-09:04",
    "type": "movie",
    "status": "copied"
  },
  {
    "year": "2014–",
    "ef": "12",
    "sf": "7",
    "Date": "2021/3/02-21:30",
    "et": "20",
    "id": "tt2805096",
    "series": "Chicago P.D.",
    "genre": "",
    "type": "series",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjI4NjY0NTktZmMwMy00Yzk1LTk5NTgtYTU5MjAzYmY4NmY4XkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_SX300.jpg",
    "status": "copied",
    "st": "7"
  },
  {
    "poster": "https://m.media-amazon.com/images/M/MV5BMTcxMTAxNzMzN15BMl5BanBnXkFtZTgwMTY1Mzk5OTE@._V1_SX300.jpg",
    "year": "2014–2017",
    "status": "processing",
    "st": "3",
    "sf": "1",
    "type": "series",
    "series": "Salem",
    "genre": "",
    "id": "tt2963254",
    "ef": "1",
    "Date": "2021/8/25-19:00",
    "et": "all"
  },
  {
    "et": "all",
    "sf": "3",
    "year": "2015–2018",
    "series": "Fortitude",
    "status": "copied",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzE1MGNmOGQtYWZkOS00MDExLWIzMjUtYmQxZTFlMzA5YjZhXkEyXkFqcGdeQXVyNjI4OTg2Njg@._V1_SX300.jpg",
    "st": "3",
    "id": "tt3498622",
    "type": "series",
    "genre": "",
    "ef": "1",
    "Date": "2021/3/27-15:04"
  },
  {
    "poster": "https://m.media-amazon.com/images/M/MV5BZDFiZTE4NWEtMGNkNC00YjhlLTk0YjMtNDA3NWRhMjc3MTM2XkEyXkFqcGdeQXVyOTA5NzQ0MDQ@._V1_SX300.jpg",
    "id": "tt3758814",
    "year": "2021",
    "priority": "false",
    "genre": "",
    "et": "0",
    "status": "copied",
    "type": "movie",
    "series": "The Ice Road",
    "Date": "2021/7/18-11:52"
  },
  {
    "et": "10",
    "id": "tt3906732",
    "sf": "1",
    "genre": "",
    "Date": "2020/11/14-16:17",
    "status": "copied",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjExMTJkMWEtYTM1Yy00YjBlLWEzOWItNGM0YzZjNzFkMjlkXkEyXkFqcGdeQXVyMTE2OTE2MzE1._V1_SX300.jpg",
    "ef": "1",
    "type": "series",
    "st": "1",
    "series": "Good Witch",
    "year": "2015–"
  },
  {
    "st": "3",
    "poster": "https://m.media-amazon.com/images/M/MV5BODk2YmE5MjEtMmQzNy00MzZjLTgxNDAtYTgzMThlZTg1M2E3XkEyXkFqcGdeQXVyMjIwNTI1MTM@._V1_SX300.jpg",
    "et": "all",
    "series": "Glitch",
    "sf": "2",
    "status": "copied",
    "genre": "",
    "id": "tt4192782",
    "Date": "2021/3/25-23:01",
    "year": "2015–2019",
    "ef": "1",
    "type": "series"
  },
  {
    "st": "6",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzM2OWM1MTUtNmNhYy00ZDJlLTgyYWQtOWY3ZmVjYjNiN2U4XkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_SX300.jpg",
    "et": "all",
    "ef": "1",
    "genre": "",
    "year": "2015–",
    "status": "copied",
    "id": "tt4477976",
    "Date": "2021/4/18-17:04",
    "type": "series",
    "sf": "4",
    "series": "Superstore"
  },
  {
    "type": "movie",
    "Date": "ETA: 10.11.2021",
    "et": "",
    "series": "Ghostbusters: Afterlife",
    "st": "",
    "year": "2021",
    "poster": "https://m.media-amazon.com/images/M/MV5BMGZmOGJjYjYtMWFkZi00NTE2LTk5NjktOGZiNDM2ZjBiMjk5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "status": "received",
    "sf": "",
    "ef": "",
    "id": "tt4513678",
    "genre": ""
  },
  {
    "et": "all",
    "id": "tt4655480",
    "st": "8",
    "Date": "2021/8/02-20:18",
    "poster": "https://m.media-amazon.com/images/M/MV5BYzMxZWM4ZmEtZWFmMS00NGZlLWI5ZWEtMzhlZDVhNGIwNWRhXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_SX300.jpg",
    "sf": "6",
    "genre": "",
    "ef": "7",
    "year": "2015–",
    "status": "copied",
    "priority": "false",
    "series": "Chicago Med",
    "type": "series"
  },
  {
    "status": "copied",
    "Date": "2021/3/27-15:11",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTVhNWRmMmUtM2IxMi00NzhiLWIyZmMtMDJkYTNlYWZiNjc5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "st": "2",
    "ef": "1",
    "year": "2016–",
    "sf": "2",
    "genre": "",
    "id": "tt4687880",
    "series": "Goliath",
    "type": "series",
    "et": "all"
  },
  {
    "type": "movie",
    "ef": "",
    "st": "",
    "sf": "",
    "Date": "2021/3/10-22:18",
    "id": "tt4736550",
    "year": "2019",
    "status": "copied",
    "et": "0",
    "series": "The Great Hack",
    "poster": "https://m.media-amazon.com/images/M/MV5BMGViZWEwOGItMGZlMC00YzE1LTk5ZWItMGYxYjhhMjBmNDMwXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_SX300.jpg",
    "genre": ""
  },
  {
    "year": "2016–2018",
    "sf": "2",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTAxNTIwNzE5MTJeQTJeQWpwZ15BbWU4MDE2NDQ2MTMy._V1_SX300.jpg",
    "ef": "1",
    "series": "StartUp",
    "st": "3",
    "type": "series",
    "id": "tt5028002",
    "Date": "2021/7/18-11:49",
    "et": "all",
    "status": "copied",
    "genre": ""
  },
  {
    "genre": "",
    "et": "all",
    "id": "tt5057054",
    "series": "Tom Clancy's Jack Ryan",
    "sf": "3",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDg1Zjc4YzktMmRmZi00ZWJmLWJiYzgtYjg3MmE0OTM1NzY5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "year": "2018–",
    "Date": "ETA Unknown",
    "type": "series",
    "ef": "1",
    "st": "3",
    "status": "received"
  },
  {
    "status": "copied",
    "ef": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BZmNmN2ZhOGYtZGJjMy00NjliLWI0ZmEtNzhmYWFiODdhNTc5XkEyXkFqcGdeQXVyNDkzNTM2ODg@._V1_SX300.jpg",
    "sf": "2",
    "st": "3",
    "type": "series",
    "id": "tt5191110",
    "year": "2016–2019",
    "series": "Berlin Station",
    "et": "all",
    "genre": "",
    "Date": "2021/3/27-14:58"
  },
  {
    "status": "copied",
    "series": "Travelers",
    "Date": "2021/5/14-20:28",
    "et": "12",
    "type": "series",
    "id": "tt5651844",
    "sf": "1",
    "st": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjUzOTQwOTg1MF5BMl5BanBnXkFtZTgwNzE4NzQ3NjM@._V1_SX300.jpg",
    "ef": "1",
    "year": "2016–2018",
    "genre": ""
  },
  {
    "poster": "https://m.media-amazon.com/images/M/MV5BYjkyOWIyZGYtYzU3ZS00NWM2LThjZGEtMDZjZjg2MTI2NzBhXkEyXkFqcGdeQXVyNjI4OTg2Njg@._V1_SX300.jpg",
    "id": "tt5712554",
    "year": "2016–",
    "type": "series",
    "series": "The Grand Tour",
    "status": "complete",
    "sf": "1",
    "et": "all",
    "ef": "1",
    "Date": "2021/8/21-10:34",
    "st": "5",
    "genre": ""
  },
  {
    "priority": "false",
    "et": "all",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDU4MWViOGItZGJjYi00YjczLTk1YmMtY2ZmNmY4YTllNDA0XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "year": "2021–",
    "series": "Jupiter's Legacy",
    "genre": "",
    "Date": "2021/5/11-19:13",
    "id": "tt5774002",
    "sf": "1",
    "type": "series",
    "status": "copied",
    "st": "1",
    "ef": "1"
  },
  {
    "status": "copied",
    "st": "3",
    "et": "all",
    "genre": "",
    "ef": "1",
    "Date": "2021/8/02-20:26",
    "year": "2016–2020",
    "poster": "https://m.media-amazon.com/images/M/MV5BN2U1ZTViMTItMDUwZC00NTBkLTlmMGItZjE2NjdmZjMxYWZkXkEyXkFqcGdeQXVyMTI5NjYwNDQ@._V1_SX300.jpg",
    "series": "Norsemen",
    "sf": "2",
    "priority": "false",
    "type": "series",
    "id": "tt5905354"
  },
  {
    "sf": "1",
    "st": "1",
    "Date": "2021/1/20-02:00",
    "status": "copied",
    "type": "series",
    "poster": "https://m.media-amazon.com/images/M/MV5BNWNhM2JiNGItMzhkNy00MzM1LThlYzYtNTNhOGNkZGRkNzI1XkEyXkFqcGdeQXVyMDE4MzA0NQ@@._V1_SX300.jpg",
    "year": "2016–",
    "series": "The Big Fat Quiz of Everything",
    "ef": "1",
    "et": "all",
    "genre": "",
    "id": "tt5974610"
  },
  {
    "id": "tt6103712",
    "status": "processing",
    "sf": "8",
    "poster": "https://m.media-amazon.com/images/M/MV5BZWExMjBjZjYtMDFiYy00ZTRhLTlhNjItNzVhZGQ5M2ZlMzNjXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_SX300.jpg",
    "genre": "",
    "year": "2016–",
    "series": "Australian Survivor",
    "type": "series",
    "Date": "2021/9/14-21:49",
    "et": "all",
    "st": "8",
    "ef": "1"
  },
  {
    "status": "received",
    "series": "Free Guy",
    "Date": "ETA Unknown",
    "sf": "",
    "ef": "",
    "et": "0",
    "year": "2021",
    "genre": "",
    "type": "movie",
    "st": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTY2NzFjODctOWUzMC00MGZhLTlhNjMtM2Y2ODBiNGY1ZWRiXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    "id": "tt6264654"
  },
  {
    "id": "tt6402468",
    "et": "0",
    "sf": "",
    "status": "copied",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDQ0MWEzMDEtMGZmNC00NjQ0LWJlNDItZDMyNDc5MmFkODJjXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    "year": "2021",
    "type": "movie",
    "series": "Blood Red Sky (DE)",
    "st": "",
    "genre": "",
    "Date": "2021/8/21-10:32",
    "ef": ""
  },
  {
    "Date": "2021/8/02-20:20",
    "series": "Good Girls",
    "type": "series",
    "ef": "1",
    "year": "2018–2021",
    "sf": "2",
    "poster": "https://m.media-amazon.com/images/M/MV5BYmFmNTVjM2ItNDNmNC00NTU3LWIwNDQtNDhlNThhNjE1MDBjXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "id": "tt6474378",
    "et": "all",
    "status": "copied",
    "genre": "",
    "st": "3"
  },
  {
    "year": "2020",
    "status": "copied",
    "genre": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BOGU3NTFmNjYtODc3Ny00MWEzLWI3M2ItZjE3NDgwMTI0MzkzXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "et": "0",
    "type": "movie",
    "series": "Monster Hunter",
    "priority": "false",
    "id": "tt6475714",
    "Date": "2021/3/07-09:25"
  },
  {
    "poster": "https://m.media-amazon.com/images/M/MV5BYTc1MmE1NGYtMzFlYS00YTNmLThjNmEtMjQ5NzY4NmJkZTIwXkEyXkFqcGdeQXVyODkxMzcxOTY@._V1_SX300.jpg",
    "genre": "",
    "status": "received",
    "ef": "1",
    "et": "all",
    "st": "5",
    "sf": "5",
    "year": "2018–",
    "series": "The Resident",
    "id": "tt6483832",
    "Date": "ETA 21.9.2021",
    "type": "series"
  },
  {
    "year": "2017–2020",
    "series": "Absentia",
    "status": "copied",
    "Date": "2021/8/02-19:59",
    "id": "tt6794990",
    "poster": "https://m.media-amazon.com/images/M/MV5BNmFiNDI5ODUtODQ2ZC00ZjUwLWFhYjQtMjk3MmMzZjY1ZWU2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "ef": "1",
    "st": "3",
    "sf": "3",
    "genre": "",
    "et": "all",
    "priority": "false",
    "type": "series"
  },
  {
    "year": "2018–",
    "genre": "",
    "Date": "2021/8/02-20:27",
    "ef": "6",
    "sf": "4",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzliYWNhMTMtNWE1MS00YjhlLTg0YTctMzI0MGUxZDNmOTdmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "st": "4",
    "et": "all",
    "status": "copied",
    "series": "Station 19",
    "type": "series",
    "id": "tt7053188",
    "priority": "false"
  },
  {
    "type": "series",
    "series": "9-1-1",
    "Date": "2021/8/02-19:56",
    "poster": "https://m.media-amazon.com/images/M/MV5BMzNiMmNmZWQtMTJlMS00NWIyLTlhNmEtNmI3M2Q1YjczMGI4XkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg",
    "genre": "",
    "st": "3",
    "et": "all",
    "year": "2018–",
    "ef": "1",
    "status": "copied",
    "id": "tt7235466",
    "sf": "1"
  },
  {
    "et": "all",
    "st": "1",
    "Date": "ETA: Nov 2021",
    "status": "received",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDQ4Mjg5NTItN2EwOC00MDdjLTk1NzEtZWExMGNhODk5MDA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "type": "series",
    "series": "The Wheel of Time",
    "ef": "1",
    "sf": "1",
    "genre": "",
    "year": "2021–",
    "id": "tt7462410"
  },
  {
    "genre": "",
    "et": "all",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjRlYWQwMTMtMmI0MC00NTBiLWEwMWItZTNjNDk0N2VmZmY3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "id": "tt7587890",
    "status": "received",
    "series": "The Rookie",
    "type": "series",
    "sf": "4",
    "year": "2018–",
    "ef": "1",
    "st": "4",
    "Date": "ETA: 26.9.2020"
  },
  {
    "id": "tt7612548",
    "status": "copied",
    "poster": "https://m.media-amazon.com/images/M/MV5BYTVhYTRmZWEtODcxZS00OWY5LTg4NzQtMmY2ZjBlYmEyMzMxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "series": "The Outpost",
    "Date": "2021/1/22-14:59",
    "type": "series",
    "sf": "1",
    "ef": "1",
    "genre": "",
    "st": "1",
    "et": "3",
    "year": "2018–"
  },
  {
    "st": "",
    "Date": "2021/6/12-10:23",
    "year": "2017",
    "status": "copied",
    "et": "0",
    "sf": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BOGE0YTBkYTItMjhiZC00NzVjLTgxYzAtZmMxNTc1YTg2MmU0XkEyXkFqcGdeQXVyMzU3MTEwNw@@._V1_SX300.jpg",
    "genre": "",
    "type": "movie",
    "series": "Flatliners: Cult Classic Visual Universe",
    "ef": "",
    "id": "tt7709504"
  },
  {
    "status": "copied",
    "id": "tt7772588",
    "et": "10",
    "ef": "1",
    "sf": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BZDMwODYyM2ItZjNlYi00YzAzLTliODItYWFkOWJiMzVhOTY0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "year": "2019–",
    "type": "series",
    "Date": "2021/3/07-09:25",
    "genre": "",
    "st": "1",
    "series": "For All Mankind"
  },
  {
    "id": "tt7817340",
    "year": "2018–",
    "genre": "",
    "Date": "2021/8/02-20:25",
    "ef": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BOWI3ZmVkNDktYTgzMy00ZTUwLThkYjQtZjI1MzMzZTNhZWVlXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_SX300.jpg",
    "et": "all",
    "st": "3",
    "sf": "3",
    "series": "New Amsterdam",
    "type": "series",
    "status": "copied"
  },
  {
    "series": "Chambers",
    "poster": "https://m.media-amazon.com/images/M/MV5BZDIzOTc3NTktOGI4MC00OTQzLWE5NzQtYTljNzI5ZGU2ZjdmXkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg",
    "status": "processing",
    "genre": "",
    "id": "tt7949204",
    "type": "series",
    "priority": "false",
    "et": "all",
    "year": "2019",
    "Date": "2021/5/29-11:36",
    "sf": "1",
    "st": "1",
    "ef": "1"
  },
  {
    "st": "1",
    "id": "tt7985576",
    "ef": "1",
    "type": "series",
    "series": "The Serpent",
    "genre": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BY2U4ZTE1YTgtNmEzZi00N2E4LTk0MWItOTY3Y2RlNzliZTZjXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg",
    "sf": "1",
    "et": "all",
    "Date": "2021/4/09-07:58",
    "status": "copied",
    "year": "2021"
  },
  {
    "type": "series",
    "Date": "2021/6/15-09:53",
    "id": "tt8128344",
    "poster": "https://m.media-amazon.com/images/M/MV5BZmQ3MTA4NDgtN2QzOS00MWE2LTg1MjktY2U3YmVjMmQ3YmU0XkEyXkFqcGdeQXVyNjcyNjcyMzQ@._V1_SX300.jpg",
    "year": "2019–",
    "series": "Flack",
    "et": "all",
    "genre": "",
    "sf": "1",
    "ef": "1",
    "status": "copied",
    "st": "2"
  },
  {
    "et": "all",
    "status": "copied",
    "priority": "false",
    "year": "2020–",
    "ef": "1",
    "id": "tt8129450",
    "st": "2",
    "Date": "2021/6/12-14:39",
    "series": "Breeders",
    "sf": "2",
    "genre": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjdkMDVmYTQtOThiOC00MTg5LTgzMDEtMzhhODcxZmMyMDBmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "type": "series"
  },
  {
    "st": "1",
    "ef": "2",
    "type": "series",
    "id": "tt8134470",
    "et": "all",
    "priority": "false",
    "year": "2020",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzY5YTcxMWYtYjFkZi00ZmI3LThmYjgtMzY0YjQzZWFkNzQ4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "status": "copied",
    "series": "The Undoing",
    "genre": "",
    "sf": "1",
    "Date": "2021/8/02-20:29"
  },
  {
    "genre": "",
    "status": "copied",
    "ef": "1",
    "et": "all",
    "priority": "false",
    "year": "2021–",
    "st": "1",
    "sf": "1",
    "series": "Fate: The Winx Saga",
    "poster": "https://m.media-amazon.com/images/M/MV5BMzEyYzBhODYtZjZlOC00MTM4LWIxMjQtMTRhZjA5ODM4ZWI2XkEyXkFqcGdeQXVyODQwODA1MjY@._V1_SX300.jpg",
    "type": "series",
    "id": "tt8179402",
    "Date": "2021/7/18-11:46"
  },
  {
    "genre": "",
    "series": "Queen Bees",
    "priority": "false",
    "id": "tt8338076",
    "type": "movie",
    "et": "0",
    "poster": "https://m.media-amazon.com/images/M/MV5BZDNiYTEyNWEtMDUwNy00Njg0LTg0YjQtMmIzNTkwZTkwY2Q0XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg",
    "Date": "2021/7/18-11:48",
    "year": "2021",
    "status": "copied"
  },
  {
    "id": "tt8368408",
    "type": "movie",
    "priority": "false",
    "status": "copied",
    "genre": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BYTE4YzczNDQtNmQzNS00ZTZjLThiMzEtOTUzOGQ5ODQzNzY1XkEyXkFqcGdeQXVyMTA3NTQ0Mzkw._V1_SX300.jpg",
    "Date": "2021/8/21-10:40",
    "et": "0",
    "series": "Gunpowder Milkshake",
    "year": "2021"
  },
  {
    "status": "copied",
    "Date": "2021/6/12-10:22",
    "priority": "false",
    "year": "2020",
    "genre": "",
    "et": "0",
    "series": "Flashback",
    "id": "tt8372094",
    "type": "movie",
    "poster": "https://m.media-amazon.com/images/M/MV5BOWZjNWFjODUtMTRhZi00MDBkLWJkYjctYmNjNmI0NWQ0NjRkXkEyXkFqcGdeQXVyOTg4MDYyNw@@._V1_SX300.jpg"
  },
  {
    "year": "2021",
    "status": "copied",
    "sf": "",
    "type": "movie",
    "id": "tt8385148",
    "ef": "",
    "Date": "2021/8/02-19:51",
    "et": "0",
    "poster": "https://m.media-amazon.com/images/M/MV5BNGQ2MGQ1ZGQtOTY4MS00ZDA5LWE5YmUtMGE0YTE2YTZiODZkXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg",
    "series": "Hitman's Wife's Bodyguard",
    "genre": "",
    "st": ""
  },
  {
    "year": "2019–",
    "Date": "2021/3/02-20:52",
    "priority": "false",
    "et": "all",
    "ef": "1",
    "id": "tt8398600",
    "st": "2",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjdjOWIxMDgtYTgwNS00MjE4LTliZWYtZGI1NDhhZmIyYjM1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "genre": "",
    "type": "series",
    "sf": "2",
    "series": "After Life",
    "status": "copied"
  },
  {
    "sf": "",
    "year": "2020",
    "series": "Eurovision Song Contest: The Story of Fire Saga",
    "Date": "2021/1/22-15:17",
    "ef": "",
    "type": "movie",
    "id": "tt8580274",
    "status": "copied",
    "et": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BYzRjYzA5NTQtOTE3MC00OTYzLWEzODItMzQxYWE1NDJkMDA0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "genre": "",
    "st": ""
  },
  {
    "st": "2",
    "Date": "2021/3/27-15:04",
    "id": "tt8594324",
    "et": "all",
    "year": "2019–",
    "series": "Ghosts",
    "type": "series",
    "genre": "",
    "poster": "https://m.media-amazon.com/images/M/MV5BYWMyZmRlMjEtMzIxNS00M2RiLWJjZjEtYzI2NDE0NGVhOGRiXkEyXkFqcGdeQXVyNjExMTQ4MjA@._V1_SX300.jpg",
    "status": "copied",
    "sf": "2",
    "ef": "1"
  },
  {
    "id": "tt8633062",
    "status": "copied",
    "sf": "1",
    "st": "1",
    "genre": "",
    "type": "series",
    "ef": "1",
    "Date": "2021/1/22-15:00",
    "et": "3",
    "priority": "false",
    "series": "The Wilds",
    "poster": "https://m.media-amazon.com/images/M/MV5BMzgzZDA2NmEtZTAwZi00ZTY3LWFiYTktNTdjYTBkNTY1N2E4XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    "year": "2020–"
  },
  {
    "ef": "4",
    "et": "all",
    "sf": "1",
    "genre": "",
    "status": "copied",
    "id": "tt8690918",
    "series": "Resident Alien",
    "type": "series",
    "Date": "2021/7/18-11:48",
    "poster": "https://m.media-amazon.com/images/M/MV5BYTFkNDFhZGEtZjA2Ni00M2Q4LWFlMWEtZGFhMmM0MWJkNDQ0XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "st": "1",
    "year": "2021–"
  },
  {
    "et": "6",
    "id": "tt8697870",
    "year": "2021–",
    "genre": "",
    "Date": "2021/4/25-11:07",
    "status": "copied",
    "st": "1",
    "series": "The Nevers",
    "type": "series",
    "poster": "https://m.media-amazon.com/images/M/MV5BODEyOWY2ZDctOGI3Zi00YjYwLWIwZDEtMzJlY2VhYTA2N2ViXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "sf": "1",
    "ef": "4"
  },
  {
    "genre": "",
    "st": "1",
    "status": "copied",
    "type": "series",
    "series": "Nine Perfect Strangers",
    "et": "4",
    "ef": "1",
    "year": "2021",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjBkYjgxNTktZjQ0Zi00OGU5LThjOTEtOGUzMDVhNjc2MjU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "Date": "2021/8/21-10:35",
    "id": "tt8760932",
    "sf": "1"
  },
  {
    "st": "2",
    "series": "Black Summer",
    "status": "copied",
    "id": "tt8923854",
    "poster": "https://m.media-amazon.com/images/M/MV5BZmI0MWNkODMtZjg4YS00ZGIzLTkxOGMtYTZmMDRmZWJjN2Q0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "year": "2019–",
    "et": "all",
    "Date": "2021/6/20-22:02",
    "ef": "1",
    "type": "series",
    "sf": "1",
    "genre": "",
    "priority": "false"
  },
  {
    "st": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjE5MjM5MzUtNjg4MS00ZWVkLTgyZWUtMGRjNzc1MzdiODNkXkEyXkFqcGdeQXVyMTMwNzQ2MDM@._V1_SX300.jpg",
    "id": "tt9055008",
    "sf": "1",
    "genre": "",
    "ef": "9",
    "type": "series",
    "series": "Evil",
    "et": "13",
    "Date": "2021/3/02-21:31",
    "status": "copied",
    "year": "2019–"
  },
  {
    "Date": "2021/3/10-22:40",
    "series": "An American Pickle",
    "id": "tt9059704",
    "priority": "false",
    "status": "copied",
    "poster": "https://m.media-amazon.com/images/M/MV5BNmRkZmZiNzUtMzgwYy00NTEzLWE2NjctMmI3NGI5ZTBiNDdkXkEyXkFqcGdeQXVyNzE3ODQxNjU@._V1_SX300.jpg",
    "type": "movie",
    "year": "2020",
    "et": "0",
    "genre": ""
  },
  {
    "st": "1",
    "id": "tt9073940",
    "Date": "2021/8/21-10:43",
    "sf": "1",
    "year": "2021–",
    "et": "all",
    "priority": "false",
    "status": "copied",
    "poster": "https://m.media-amazon.com/images/M/MV5BNGRlMzMzMWUtNTg0NC00ODdhLTllNzQtYTA4NWIwNjk5Y2JhXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg",
    "series": "Hit and Run",
    "ef": "1",
    "type": "series",
    "genre": ""
  },
  {
    "type": "series",
    "et": "16",
    "st": "3",
    "ef": "4",
    "year": "2019–",
    "id": "tt9111220",
    "Date": "2021/8/21-10:39",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDQxYjZjZDgtYzA1MS00NjMxLWE5NDYtMTlkZWZiMDhhMjk3XkEyXkFqcGdeQXVyNDkwNzc5OQ@@._V1_SX300.jpg",
    "sf": "2",
    "series": "Hudson & Rex",
    "genre": "",
    "status": "complete"
  },
  {
    "status": "copied",
    "priority": "false",
    "poster": "https://m.media-amazon.com/images/M/MV5BNTkwOTE1ZDYtODQ3Yy00YTYwLTg0YWQtYmVkNmFjNGZlYmRiXkEyXkFqcGdeQXVyNTc4MjczMTM@._V1_SX300.jpg",
    "id": "tt9140554",
    "et": "all",
    "ef": "1",
    "st": "1",
    "genre": "",
    "sf": "1",
    "year": "2021–",
    "Date": "2021/8/02-20:39",
    "type": "series",
    "series": "Loki"
  },
  {
    "id": "tt9165444",
    "genre": "",
    "Date": "2021/8/02-20:00",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjE5MzU4M2EtMTM0ZS00Y2MxLWJkOGItYWY0MGYzZGQwYjYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "type": "series",
    "st": "1",
    "series": "Almost Family",
    "sf": "1",
    "ef": "8",
    "year": "2019–2020",
    "status": "copied",
    "et": "all"
  },
  {
    "et": "all",
    "year": "2020–",
    "sf": "1",
    "type": "series",
    "id": "tt9170108",
    "Date": "2021/1/12-20:59",
    "genre": "",
    "st": "1",
    "priority": "false",
    "ef": "1",
    "status": "copied",
    "series": "Raised by Wolves",
    "poster": "https://m.media-amazon.com/images/M/MV5BYWUzMGZjNjgtMzkwYS00MTdhLTlhYzItYTEzMjRjMjkzZmM3XkEyXkFqcGdeQXVyMTE5MzYzMDE5._V1_SX300.jpg"
  },
  {
    "id": "tt9214832",
    "Date": "2021/6/12-10:25",
    "type": "movie",
    "status": "copied",
    "series": "Emma.",
    "priority": "false",
    "year": "2020",
    "et": "0",
    "poster": "https://m.media-amazon.com/images/M/MV5BOGRiODEzM2QtOTUyYi00MWRlLTg4MzMtZGI0YmUzNWUyMjQ0XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg",
    "genre": ""
  },
  {
    "status": "copied",
    "id": "tt9251798",
    "poster": "https://m.media-amazon.com/images/M/MV5BODM3NTZkZTUtYzEyYS00NjEyLTg2NjEtNDhlMjYwY2ZkNGUzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "sf": "1",
    "ef": "1",
    "Date": "2020/11/14-16:14",
    "series": "Ragnarok",
    "type": "series",
    "st": "1",
    "et": "6",
    "year": "2020–",
    "genre": ""
  },
  {
    "status": "copied",
    "priority": "false",
    "et": "0",
    "series": "Palm Springs",
    "Date": "2021/3/10-22:41",
    "id": "tt9484998",
    "genre": "",
    "type": "movie",
    "year": "2020",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjk0MTgzMmQtZmY2My00NmE5LWExNGUtYjZkNTA3ZDkyMTJiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg"
  },
  {
    "et": "all",
    "series": "Space Force",
    "ef": "1",
    "year": "2020–",
    "status": "received",
    "sf": "2",
    "id": "tt9612516",
    "poster": "https://m.media-amazon.com/images/M/MV5BNWYwMzE2MGItOTYwYy00YmQyLWE0NGQtZWViMTU4ZTk4ZjQxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "st": "2",
    "type": "series",
    "Date": "ETA Unknown",
    "genre": ""
  },
  {
    "series": "Behind Her Eyes",
    "Date": "2021/3/10-23:23",
    "id": "tt9698442",
    "year": "2021",
    "genre": "",
    "sf": "1",
    "status": "copied",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDk2Njg0ZTUtNTFjZS00NzUwLWEwZDQtZTg5MDZiMmJhNGEzXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg",
    "ef": "1",
    "type": "series",
    "st": "1",
    "et": "6"
  },
  {
    "series": "The Vault (Way Down)",
    "id": "tt9742794",
    "status": "copied",
    "genre": "",
    "Date": "2021/4/18-17:01",
    "poster": "https://m.media-amazon.com/images/M/MV5BZTliM2M5MjktZmY2NC00NjdlLWE5YzUtNDU2NzA0MzkyMDNlXkEyXkFqcGdeQXVyMTE1Nzg4NjY0._V1_SX300.jpg",
    "year": "2021",
    "ef": "",
    "et": "0",
    "st": "",
    "type": "",
    "sf": ""
  },
  {
    "year": "2021",
    "status": "copied",
    "priority": "false",
    "genre": "",
    "id": "tt9777666",
    "poster": "https://m.media-amazon.com/images/M/MV5BNTI2YTI0MWEtNGQ4OS00ODIzLWE1MWEtZGJiN2E3ZmM1OWI1XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    "type": "movie",
    "et": "0",
    "series": "The Tomorrow War",
    "Date": "2021/7/18-11:46"
  },
  {
    "st": "2",
    "status": "complete",
    "ef": "1",
    "year": "2020–",
    "type": "series",
    "sf": "1",
    "poster": "https://m.media-amazon.com/images/M/MV5BZTBmYTYzZGUtOThlZC00YzVmLWFmMWItZTEwYWRlOGVlNDViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "genre": "",
    "Date": "2021/8/30-18:34",
    "id": "tt9900092",
    "series": "Motherland: Fort Salem",
    "et": "all"
  }
])
  let titleList = Array.from(
    new Set(bigDbArray.map(entry => entry["series"]))
  );

  titleList.forEach(title => {
    let downloadedList = bigDbArray.filter(
      entry => entry["series"] === title["series"]
    );
    if (downloadedList[0]["type"] === "series") {
      let range = { sf: 0, ef: 0, st: 0, et: 0 };
      let episodesObj = {};
      downloadedList.forEach(listItem => {
        const { sf, ef, st, et } = listitem;
        range["sf"] = Math.min(sf, range["sf"]);
        range["st"] = Math.max(st, range["st"]);
        if (!episodesObj.hasOwnProperty(sf) && sf === st) {
          episodesObj[sf] = { min: ef, max: et, status: listItem["status"] };
        } else if (!episodesObj.hasOwnProperty(sf) && sf !== st) {
          episodesObj[sf] = { min: ef, status: listItem["status"] };
        } else if (!episodesObj.hasOwnProperty(st) && sf !== st) {
          episodesObj[st] = { max: et, status: listItem["status"] };
        }
        if (episodesObj.hasOwnProperty(sf) && sf === st) {
          if (episodesObj[sf].hasOwnProperty("min")) {
            episodesObj[sf]["min"] = Math.min(episodesObj[sf]["min"], ef);
          } else {
            episodesObj[sf]["min"] = ef;
          }
          if (episodesObj[sf].hasOwnProperty("max")) {
            episodesObj[sf]["status"] = listItem["status"];
            if (et !== "all" && episodesObj[sf]["max"] !== "all") {
              episodesObj[sf]["max"] = Math.max(episodesObj[sf]["max"], et);
            }
          }
        } else if (episodesObj.hasOwnProperty(st)) {
          episodesObj[st]["status"] = listItem["status"];
          if (!episodesObj[st].hasOwnProperty("max")) {
            if (et !== "all" && episodesObj[st]["max"] !== "all") {
              episodesObj[st]["max"] = Math.max(episodesObj[sf]["max"], et);
            }
          }
        }
      });

      let newEpisodesObj = {};
      Object.keys(episodesObj).forEach(season => {
        newEpisodesObj[season] = createRangeObj(
          season,
          episodesObj[season]["min"],
          episodesObj[season]["max"],
          episodesObj[season]["status"],
          imdbID
        );
      });
      downloadedList[0]["episodes"] = newEpisodesObj;
      FinalList.push(fixFields(downloadedList[0]));
    } else {
      FinalList.push(fixFields(downloadedList[0]));
    }
  });
  return FinalList;
}

const statusConverter = {
  received: "new",
  processing: "downloading",
  complete: "complete",
  copied: "copied",
  archived: "copied"
};

function createRangeObj(efArg, etArg, status) {
  let ef = parseInt(ef) !== NaN ? parseInt(efArg) : 1;
  let et = parseInt(ef) !== NaN ? parseInt(efArg) : ef;

  let obj = {};
  for (let index = ef; index <= et; index++) {
    obj[index] = status;
  }
  return obj;
}

function fixFields(data) {
  let obj = {};
  obj.addedBy = "Antje";
  obj.id = v4();
  obj.mediaType = data["type"];
  let status = statusConverter[data["status"]];
  if (
    data["id"].slice(0, 1) === "tt" &&
    parseInt(data["id"].slice(2)) !== NaN
  ) {
    obj.imdbID = data["id"];
  } else {
    obj.imdbID = "noimdbinfo";
  }
  obj.name = data["series"];
  obj.dateAdded = data["Date"];
  obj.imdbData = {
    Poster: data["poster"],
    Year: data["year"],
    imdbID: data["id"]
  };
  obj.isPriority = data["priority"];
  if (data.mediaType !== "movie") {
    obj.sf = data.sf;
    obj.ef = data.ef;
    obj.st = data.st;
    obj.et = data.et;
    obj.isOngoing = false;
    obj.episodes = data["episodes"];
  }
  return obj;
}
